filters:
  - type: "data_cleaning.annotation_standard"
    parameters:
      bounding_box_format: "XYXY"
      bounding_box_coordinate_system: "Continuous"

datasets:
  - name: "GOT10k"
    type: "SOT"
    splits:
      - "train"
    parameters:
      data_specs: "got10k_min_split"
